#!/bin/bash

sudo apt update && sudo apt -y install openjdk-17-jdk zip

wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip
unzip apache-maven-3.9.6-bin.zip
ln -s $(pwd)/apache-maven-3.9.6/bin/mvn $(echo $PATH | awk -F ":" {'print $1'})
mvn -v
